ARG  BUILDER_IMAGE=pytorch/pytorch:2.0.1-cuda11.7-cudnn8-devel
FROM ${BUILDER_IMAGE} AS builder

RUN echo $PYTORCH_VERSION
RUN echo $NVIDIA_VISIBLE_DEVICES

RUN apt-get -y update; apt-get -y install curl

ENV POETRY_HOME="/workspace/.local/pypoetry"
RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH=$POETRY_HOME/bin:$PATH
RUN poetry --version

COPY Makefile poetry.lock pyproject.toml src/ ./
RUN poetry run poetry install --no-interaction --all-extras
