_target_: gravitorch.creators.model.DataDistributedParallelModelCreator
model_creator:
  _target_: gravitorch.creators.model.VanillaModelCreator
  model_config: ${model}
  attach_model_to_engine: true
  add_module_to_engine: true
  device_placement: ${oc.select:device_placement,null}
ddp_kwargs:
  find_unused_parameters: false
