_target_: gravitorch.loops.evaluation.FabricEvaluationLoop
grad_enabled: false
condition:
  _target_: gravitorch.loops.evaluation.conditions.EveryEpochEvalCondition
  every: 1
profiler: null
observer: null

