_target_: gravitorch.runners.EvaluationRunner
engine: ${engine}
handlers: ${oc.dict.values:handler}
exp_tracker: ${oc.select:exp_tracker,null}
random_seed: ${oc.select:random_seed,42}
log_only_main_process: true
