_target_: gravitorch.utils.parameter_initializers.SequentialParameterInitializer
parameter_initializers:
  - _target_: gravitorch.utils.parameter_initializers.XavierUniformParameterInitializer
    gain: 1.0
    learnable_only: true
    show_stats: false
  - _target_: gravitorch.utils.parameter_initializers.ConstantBiasParameterInitializer
    value: 0.0
    log_info: true
    learnable_only: true
    show_stats: false
