- _target_: gravitorch.experimental.rsrc.LogSysInfo
- _target_: gravitorch.experimental.rsrc.LogCudaMemory
- _target_: gravitorch.experimental.rsrc.Logging
  only_main_process: true
- _target_: gravitorch.experimental.rsrc.PyTorchConfig
- _target_: gravitorch.experimental.rsrc.PyTorchCudaBackend
  allow_tf32: true
  log_info: true
- _target_: gravitorch.experimental.rsrc.PyTorchCudnnBackend
  allow_tf32: true
  benchmark: true
  enabled: true
  log_info: true
- _target_: gravitorch.experimental.rsrc.DistributedContext
  backend: auto
  log_info: true
