name: Nightly Tests
on:
  schedule:
    - cron: '30 9 * * *' # run at 9:30 AM UTC
  workflow_dispatch:  # manual trigger

jobs:
  cyclic-imports:
    uses: ./.github/workflows/cyclic-imports.yaml
  doctest:
    uses: ./.github/workflows/doctest.yaml
  experiment:
    uses: ./.github/workflows/experiment.yaml
  format:
    uses: ./.github/workflows/format.yaml
  test:
    uses: ./.github/workflows/test.yaml
  test-deps:
    uses: ./.github/workflows/test-deps.yaml
